### PR TITLE
Bumped Nidhogg version, pointed to newest Lightvessel version and added flag for circular dependency

### PR DESCRIPTION
**Pull request by jaxels10**
Added flag to decide if circular reference to monitor nidhogg should be enabled.
I have bumped nidhoggs version to fix the error of the overwritten values. The relevant pull-request in Nidhogg was [this](https://github.com/distributed-technologies/helm-charts/pull/218). 
In the commit that was made, a bump to ntp version was included, but it is not shown in the files changed, cause it has already been merged into the main branch.
Bumped lightvessel version to allow ingress to not be created

### CODE REVIEW

**Review by skovbakke — CHANGES_REQUESTED** [review]
Cannot merge since there are conflicts. Instead of bumping the version twice I suggest we rebase. 

More importantly, the commit message for the actual change should be improved: It would be great to have some context i.e. describe the issue, where it came from, and how this solves it.

**Comment by klausenbusk** [comment]
> It would be great to have some context i.e. describe the issue, where it came from, and how this solves it.

I agree, context is needed, but I don't like duplicating the commit messages from helm-charts, just referring to them should be enough, ex: https://github.com/distributed-technologies/yggdrasil/commit/9e4757a3a1fd5fb2fa12d7d4370da8bb1049a249.

**Comment by jaxels10** [comment]
I have updated the message on the pull request on nidhogg that actually fixed this to be more meaningful. I have also added a link to that PR on this PR. I agree that whenever we bump Nidhogg and Yggdrasil to point to a new version of a chart that has had something fixed, we should include a link to them in the yggdrasil PR.

**Comment by skovbakke** [comment]
@jaxels10 It would be great if you would edit the actual commit message and not only the PR message, currently it is: "Added new line". That is the one I was referring to.

**Comment by jaxels10** [comment]
> @jaxels10 It would be great if you would edit the actual commit message and not only the PR message, currently it is: "Added new line". That is the one I was referring to.

I misunderstood. I have now edited the actual commit message.

**Comment by skovbakke** [comment]
Thank you, for updating the commit message. To be honest though, reading this:
```
commit 0c1149be6fe0ad1e4bd235546dacbb45f6e2f44a

    Added flag to decide if circular reference to monitor nidhogg should be enabled.
    I have bumped nidhoggs version to fix the error of the overwritten values. The relevant pull-request in Nidhogg was this.
    Bumped ntp version to include Kristians changes to that
    Bumped lightvessel version to allow ingress to not be created
``` 
confuses me more than it clarifies, e.g. 
* What does ntp have to do with this? (no files related to ntp are changed in this PR) 
* How are lightvessel and ingress related to the "error of the overwritten values"?
* Also hyperlinks like [this](https://github.com/distributed-technologies/nidhogg/pull/218) do not work in commit messages, consider using a syntax like in this [commit](https://github.com/distributed-technologies/yggdrasil/commit/f735864f742c221f620d821c727e6683d8a436c7).

After having looked carefully at the changes made here and in nidhogg and lightvessel. I believe, and correct me if I am wrong, that this PR does nothing, except bumping the version?

**Comment by jaxels10** [comment]
> Thank you, for updating the commit message. To be honest though, reading this:
> 
> ```
> commit 0c1149be6fe0ad1e4bd235546dacbb45f6e2f44a
> 
>     Added flag to decide if circular reference to monitor nidhogg should be enabled.
>     I have bumped nidhoggs version to fix the error of the overwritten values. The relevant pull-request in Nidhogg was this.
>     Bumped ntp version to include Kristians changes to that
>     Bumped lightvessel version to allow ingress to not be created
> ```
> 
> confuses me more than it clarifies, e.g.
> 
> * What does ntp have to do with this? (no files related to ntp are changed in this PR)
> * How are lightvessel and ingress related to the "error of the overwritten values"?
> * Also hyperlinks like [this](https://github.com/distributed-technologies/nidhogg/pull/218) do not work in commit messages, consider using a syntax like in this [commit](https://github.com/distributed-technologies/yggdrasil/commit/f735864f742c221f620d821c727e6683d8a436c7).
> 
> After having looked carefully at the changes made here and in nidhogg and lightvessel. I believe, and correct me if I am wrong, that this PR does nothing, except bumping the version?

* In the commit for this PR, there is a bump for the NTP version in Yggdrasil. However, I had not noticed that this bump had already happened on the main branch and is therefore not reflected in the "files changed". I have removed it from the pull request, but left it in the commit message as the change is still reflected there. 
* Lightvessel and Ingress are not related to that error at all. This PR has ended up including multiple version/dependency bumps, since it seemed easier to just include in an already existing PR. While I did consider making multiple pull requests, it seemed unnecessary to do so just for the sake of a single version bump. It is probably a good practice to just keep a pull request related to a single issue, but I also think we should probably talk about our process for how single version bump pull requests are reviewed, as they can sometimes block another task and it currently takes a long time for any task to go through a review process, even if it is small. 
* I will update the commit message with the correct syntax on Monday :-)

**Comment by jaxels10** [comment]
Closing this PR since the changes were implemented in https://github.com/distributed-technologies/yggdrasil/pull/58

**Pull request closed without merging**
