### PR TITLE
Correct linting errors

### PR DESCRIPTION
**Pull request by skovbakke**
This is a PR for fixing linting errors.

### CODE REVIEW

**Comment by jaxels10** [comment]
I have fixed the linting errors in both yggdrasil and nidhogg but FYI the linter does not lint the applications/ and services/ folders in yggdrasil since they are not a part of the regular helm chart structure.

**Comment by skovbakke** [comment]
I have fixed trailing whitespace errors and missing end of file newlines in all files. However, some errors remain, since the linter does not work great with helm templates. See e.g. [this](https://github.com/sbaudoin/yamllint/issues/16).

**Comment by skovbakke** [comment]
I removed the `yamllint` step on all yaml-files. It is not able to process the helm templating code. And since we use helm templating code everywhere it is better to avoid the false errors.

**Review by klausenbusk — APPROVED** [review]
LGTM 🎉

**Pull request merged**
